"""Add grade table and update student, subject models

Revision ID: 38ec0f45fd4c
Revises: 
Create Date: 2025-11-17 14:21:58.431741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ec0f45fd4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False, comment='Điểm số'),
    sa.Column('grade_type', sa.String(length=50), nullable=True, comment='Loại điểm: 15 phút, 1 tiết, học kỳ,...'),
    sa.Column('term', sa.String(length=50), nullable=True, comment='Học kỳ: I, II, Hè'),
    sa.Column('exam_date', sa.Date(), nullable=True, comment='Ngày kiểm tra'),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Ngày sinh của học sinh'))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True, comment='Giới tính: Nam, Nữ, Khác'))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True, comment='Phân loại môn học: Tự nhiên, Xã hội,...'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')

    op.drop_table('grades')
    # ### end Alembic commands ###
