"""Add class_id to Session mode

Revision ID: c90562b345e0
Revises: 38ec0f45fd4c
Create Date: 2025-12-24 15:24:20.890010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c90562b345e0'
down_revision = '38ec0f45fd4c'
branch_labels = None
depends_on = None

# trong file c90562b345e0_....py
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        # SỬA Ở ĐÂY: Thêm server_default='1'
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_sessions_classes', 'classes', ['class_id'], ['id']) # Đặt tên cho FK

    # Sau khi thêm cột với giá trị mặc định, chúng ta không cần nó nữa
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('class_id', server_default=None)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('class_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               comment='Tên lớp, ví dụ: 10/1',
               existing_comment='Tên lớp, ví dụ: 9/1',
               existing_nullable=False)

    # ### end Alembic commands ###
